### PR TITLE
Automated license headers CI

### LINKED ISSUE #69: Auto license
This issue is spawned from issue #45 to add automated license statements to the top of all files.

### PR DESCRIPTION
**Pull request by zachcran**
**Is this pull request associated with an issue(s)?**
Closes #69.

**Description**
This PR adds a CI workflow that automatically adds the Apache License, Version 2.0 copyright notice to the top of all files that are not in the `.github/.licenserc.yaml` file. This workflow is copied from CMakePPLang, but the ignored files are modified for this repository.

**TODOs**
- [x] Verify that the correct files are being ignored.

### CODE REVIEW

**Comment by zachcran** [comment]
Does this invalidate `bin/apply_license.py`? ([here](https://github.com/CMakePP/CMakeTest/blob/master/bin/apply_license.py))

**Comment by ryanmrichard** [comment]
@zachcran yeah I think we should get rid of apply_license.py

**Review by ryanmrichard — APPROVED** [review]

**Comment by zachcran** [comment]
While we're at it, should we just delete everything in `bin/`? It seems like they are all obsolete scripts now.

**Comment by ryanmrichard** [comment]
@zachcran sounds good to me, but @AutonomicPerfectionist should confirm.

**Review by AutonomicPerfectionist — APPROVED** [review]
Looks good to me

**Pull request merged**
